development:
  adapter: postgresql
  encoding: unicode
  database: Receipe_App_development
  host: localhost
  pool: 5432
  username: postgres
  password: koko23052020

test:
  adapter: postgresql
  encoding: unicode
  database: Receipe_App_test
  pool: 5432
  username: postgres
  password: koko23052020

production:
  adapter: postgresql
  encoding: unicode
  database: Receipe_App_production
  pool: 5432
  username: postgres
  password: koko23052020
